theme: jekyll-theme-minimal
title: Lorence Cramwinckel
description: Active entrepreneur in areas of so1ware development and hospitality. Gained managerial experience from a young age saving the family business. Disciplined and a fast learner with a rich interna$onal background and a strong ability to perform under pressure.
logo: assets/profile.png
show_downloads: "false"
