theme: jekyll-theme-minimal
title: Lorence Cramwinckel
description: <br>Active entrepreneur in areas of software development and hospitality. Gained managerial experience from a young age saving the family business.
logo: assets/profile.png
show_downloads: "false"
